### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by fritx** [fritx/markppt#1]
- [x] 前端加载markdown 98218176569973fc8470f04fb80cdbc5ba1e95fa
- [x] location.hash播放控制 ffefe49c538327581b97048a38fc19e26aa5b08f (ipad:chrome hash卡顿
- [x] 鼠标滚轮播放控制 6b606af2d375a90eb8b440120885fcd807911a05 (敏感度过高 忽略e.ctrlKey
- [x] 移动端touch播放控制 518d7a2334251d3a20f40d068dd6034f3ccef6d0
- [x] css主题选择 fb48e8aff066c7375a4b2ae9f2b15728a339ea99 (dark为默认
- [x] 切换动画改为slide fdff0346ad16cdbb12daadeec3ccecbfd855df74 (横竖屏判断?
- [x]  logo制作 #2 (thanks @Jayin 
- [x] 微信分享holder 735853d7aa3227dce1036b322f14da3b95d75aab
- [x] 引入minimist选项 hrOnly自动判断hack 40053da860707736dd043f151c43366e93e16f7a
- [x] 代码块高亮显示 66802f39f40089464ccb59dc0026cff4a759237a
- [x] 每一页内使用 [$.waitForimages](https://github.com/alexanderdickson/waitForImages) 294ef02ae21961abe569b51c974cb6dd5e7338b3
- [x] 随机背景色randomColor.js 支持theme/color选项  ae7df02b5577cb6ce41dde6da60345365243b40b (更新doc
- [x] 安卓微信+ie 显示bug (html5元素display:block 442f07e9d1ad6eac747e56b6306b7b9099b8ef5e
- [x] html模板抽离@Jayin #3 1aba52d15f93937adea92cbe4bd7bfb9179ed55a
- [x] 加入gitter/github/npm徽章 8f7d6bf33be72efc89d54f7bc1c8ae21095d71aa d0476dc5da3c6a2881d1668a4ebc613ecbb05991
- [ ] 播放进度显示 顶部pace.js? @huangruichang 
- [ ] 命令行 判断input文件 不存在则中断 @jacsonLee 
- [ ] 安卓微信 代码块水平滑动 页面白色闪动
- [ ] 安卓微信 代码块 盒模型bug
- [ ] 安卓chrome 代码块偶尔不能水平滑动
- [ ] 代码块水平滚动条样式兼容问题 (需强制隐藏
- [ ] 响应式缩放算法改进
- [ ] markdown或img 404效果 加载判断
- [ ] wifi建议/无网络判断 提示
- [ ] 小屏幕table水平滑动
- [ ] 播放中keynote提示
- [ ] 在线转换服务站点 @Jayin 
- [ ] express式的中间件机制 插件剥离

**Comment by fritx** [comment]
@huangruichang @Jayin @jacsonLee 有没人来加入哈 我喜欢开源氛围

**Comment by huangruichang** [comment]
没有播放进度？

**Comment by fritx** [comment]
@huangruichang 可以有呀:+1: 因为我个人的话觉得不是必须 所以暂时没列
我觉得可以用这个功能 有个toggle接口（编译前/运行时都行）给到用户就好了

**Comment by Jayin** [comment]
- 在线转换服务站点
  这个设计目标应该是能跑coding?

**Comment by fritx** [comment]
@Jayin 嗯 没错 要在coding上跑先 你来架构？

**Comment by Jayin** [comment]
那么需求是啥？

我上传一份mardown，然后生成一份html? 然后放在静态文件服务器上？ right?

**Comment by fritx** [comment]
嗯 是的 不过也要支持zip包解压 因为本地图片需要一起打包上传
把链接给到用户就可以了

**Comment by fritx** [comment]
touch播放控制 这个要不就先用着类似[拉勾网](https://github.com/fritx/lift)的简单效果吧 (√)

**Comment by jacsonLee** [comment]
自动播放？

**Comment by fritx** [comment]
@jacsonLee 酷炫！
我发现选项越来越多了 无法抑制 引入个markppt.json配置如何？类似package.json/bower.json
生成的时候直接$ markppt file 就可以了
- theme: css主题 目前只有dark和light
- animation: 切换动画
- pagination: 分页模式 h1~h6/hr
- progress: 显示播放进度?
- autoplay: 自动播放?

**Comment by Jayin** [comment]
> 引入markppt.json

+1

**Comment by fritx** [comment]
@Jayin 在线服务有在架构吗？
我明天talk可能要拿这个做demo现场速码 如果你没开始的话可以等俺这个先出来

**Comment by Jayin** [comment]
你先来

**Comment by fritx** [comment]
~~animate.css不支持ie 换用velocity.js??~~ https://github.com/daneden/animate.css/issues/401#issuecomment-98701785
animate.css是支持新版ie的 还是markppt自身兼容问题

**Comment by Jayin** [comment]
啥问题呢？卡顿？

**Comment by fritx** [comment]
显示的时候错乱 ie/安卓微信..

**Comment by fritx** [comment]
英爷来个html模板文件？
昌爷来个进度条？
雄爷帮判断文件存在

**Comment by Jayin** [comment]
html 模板用啥好？

**Comment by fritx** [comment]
follow your heart ;)

**Comment by jacsonLee** [comment]
我试试 趁在学校远程 可以偷懒！ 现在撸！

**Comment by Jayin** [comment]
进度条: https://github.com/rstacruz/nprogress

**Comment by fritx** [comment]
woo 昌爷说这个[pace](https://github.com/HubSpot/pace) 好像都很吊

**Comment by fritx** [comment]
大家暂时不用管master分支 在dev上pull request就行

**Comment by fritx** [comment]
gitter聊天室 [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/fritx/markppt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
http://badge.fury.io/for/js/markppt 这个徽章服务也不错 可以考虑fork一些创意出来玩
